//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the minrob_cv package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __minrob_cv__IMAGEPROCESSORCONFIG_H__
#define __minrob_cv__IMAGEPROCESSORCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace minrob_cv
{
  class ImageProcessorConfigStatics;

  class ImageProcessorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(ImageProcessorConfig &config, const ImageProcessorConfig &max, const ImageProcessorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ImageProcessorConfig &config1, const ImageProcessorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ImageProcessorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ImageProcessorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ImageProcessorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ImageProcessorConfig &config) const = 0;
      virtual void getValue(const ImageProcessorConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ImageProcessorConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (ImageProcessorConfig::* field);

      virtual void clamp(ImageProcessorConfig &config, const ImageProcessorConfig &max, const ImageProcessorConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ImageProcessorConfig &config1, const ImageProcessorConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ImageProcessorConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ImageProcessorConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ImageProcessorConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ImageProcessorConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ImageProcessorConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ImageProcessorConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ImageProcessorConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ImageProcessorConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ImageProcessorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class HSV
{
  public:
    HSV()
    {
      state = true;
      name = "hsv";
    }

    void setParams(ImageProcessorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("h_max"==(*_i)->name){h_max = boost::any_cast<int>(val);}
        if("h_min"==(*_i)->name){h_min = boost::any_cast<int>(val);}
        if("s_max"==(*_i)->name){s_max = boost::any_cast<int>(val);}
        if("s_min"==(*_i)->name){s_min = boost::any_cast<int>(val);}
        if("v_max"==(*_i)->name){v_max = boost::any_cast<int>(val);}
        if("v_min"==(*_i)->name){v_min = boost::any_cast<int>(val);}
      }
    }

    int h_max;
int h_min;
int s_max;
int s_min;
int v_max;
int v_min;

    bool state;
    std::string name;

    
}hsv;

}groups;



//#line 22 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      int h_max;
//#line 23 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      int h_min;
//#line 24 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      int s_max;
//#line 25 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      int s_min;
//#line 26 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      int v_max;
//#line 27 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      int v_min;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ImageProcessorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ImageProcessorConfig &__max__ = __getMax__();
      const ImageProcessorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ImageProcessorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ImageProcessorConfig &__getDefault__();
    static const ImageProcessorConfig &__getMax__();
    static const ImageProcessorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ImageProcessorConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ImageProcessorConfig::ParamDescription<std::string>::clamp(ImageProcessorConfig &config, const ImageProcessorConfig &max, const ImageProcessorConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ImageProcessorConfigStatics
  {
    friend class ImageProcessorConfig;

    ImageProcessorConfigStatics()
    {
ImageProcessorConfig::GroupDescription<ImageProcessorConfig::DEFAULT, ImageProcessorConfig> Default("Default", "", 0, 0, true, &ImageProcessorConfig::groups);
ImageProcessorConfig::GroupDescription<ImageProcessorConfig::DEFAULT::HSV, ImageProcessorConfig::DEFAULT> hsv("hsv", "", 0, 1, true, &ImageProcessorConfig::DEFAULT::hsv);
//#line 22 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __min__.h_max = 0;
//#line 22 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __max__.h_max = 179;
//#line 22 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __default__.h_max = 179;
//#line 22 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      hsv.abstract_parameters.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("h_max", "int", 0, "Maximum hue.", "", &ImageProcessorConfig::h_max)));
//#line 22 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __param_descriptions__.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("h_max", "int", 0, "Maximum hue.", "", &ImageProcessorConfig::h_max)));
//#line 23 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __min__.h_min = 0;
//#line 23 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __max__.h_min = 179;
//#line 23 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __default__.h_min = 0;
//#line 23 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      hsv.abstract_parameters.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("h_min", "int", 0, "Minimum hue.", "", &ImageProcessorConfig::h_min)));
//#line 23 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __param_descriptions__.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("h_min", "int", 0, "Minimum hue.", "", &ImageProcessorConfig::h_min)));
//#line 24 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __min__.s_max = 0;
//#line 24 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __max__.s_max = 255;
//#line 24 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __default__.s_max = 255;
//#line 24 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      hsv.abstract_parameters.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("s_max", "int", 0, "Maximum saturation.", "", &ImageProcessorConfig::s_max)));
//#line 24 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __param_descriptions__.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("s_max", "int", 0, "Maximum saturation.", "", &ImageProcessorConfig::s_max)));
//#line 25 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __min__.s_min = 0;
//#line 25 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __max__.s_min = 255;
//#line 25 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __default__.s_min = 0;
//#line 25 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      hsv.abstract_parameters.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("s_min", "int", 0, "Minimum saturation.", "", &ImageProcessorConfig::s_min)));
//#line 25 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __param_descriptions__.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("s_min", "int", 0, "Minimum saturation.", "", &ImageProcessorConfig::s_min)));
//#line 26 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __min__.v_max = 0;
//#line 26 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __max__.v_max = 255;
//#line 26 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __default__.v_max = 255;
//#line 26 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      hsv.abstract_parameters.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("v_max", "int", 0, "Maximum value.", "", &ImageProcessorConfig::v_max)));
//#line 26 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __param_descriptions__.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("v_max", "int", 0, "Maximum value.", "", &ImageProcessorConfig::v_max)));
//#line 27 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __min__.v_min = 0;
//#line 27 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __max__.v_min = 255;
//#line 27 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __default__.v_min = 0;
//#line 27 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      hsv.abstract_parameters.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("v_min", "int", 0, "Minimum value.", "", &ImageProcessorConfig::v_min)));
//#line 27 "/home/noah/RV_CV_Assignment_2_ws/src/minrob_cv/cfg/ImageProcessor.cfg"
      __param_descriptions__.push_back(ImageProcessorConfig::AbstractParamDescriptionConstPtr(new ImageProcessorConfig::ParamDescription<int>("v_min", "int", 0, "Minimum value.", "", &ImageProcessorConfig::v_min)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      hsv.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ImageProcessorConfig::AbstractGroupDescriptionConstPtr(new ImageProcessorConfig::GroupDescription<ImageProcessorConfig::DEFAULT::HSV, ImageProcessorConfig::DEFAULT>(hsv)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ImageProcessorConfig::AbstractGroupDescriptionConstPtr(new ImageProcessorConfig::GroupDescription<ImageProcessorConfig::DEFAULT::HSV, ImageProcessorConfig::DEFAULT>(hsv)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ImageProcessorConfig::AbstractGroupDescriptionConstPtr(new ImageProcessorConfig::GroupDescription<ImageProcessorConfig::DEFAULT, ImageProcessorConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ImageProcessorConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ImageProcessorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ImageProcessorConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ImageProcessorConfig __max__;
    ImageProcessorConfig __min__;
    ImageProcessorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ImageProcessorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ImageProcessorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ImageProcessorConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ImageProcessorConfig &ImageProcessorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ImageProcessorConfig &ImageProcessorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ImageProcessorConfig &ImageProcessorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ImageProcessorConfig::AbstractParamDescriptionConstPtr> &ImageProcessorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ImageProcessorConfig::AbstractGroupDescriptionConstPtr> &ImageProcessorConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ImageProcessorConfigStatics *ImageProcessorConfig::__get_statics__()
  {
    const static ImageProcessorConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ImageProcessorConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __IMAGEPROCESSORRECONFIGURATOR_H__
